workspace = { members = ["example"] }
[package]
name = "retro_ab_av"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.86"
gl = "0.14.0"
retro_ab = { path = "../retro_ab" }
sdl2 = "0.36.0"


[[example]]
name = "example"
path = "example/src/main.rs"
