workspace = { members = ["example"] }
[package]
name = "retro_ab_av"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.34.0"
winit = "0.29.12"
retro_ab = { path = "../retro_ab" }

[[example]]
name = "example"
path = "example/src/main.rs"
